// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grctqmsohwqbhtljumbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyY3RxbXNvaHdxYmh0bGp1bWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTIzNTksImV4cCI6MjA3NTMyODM1OX0.qC1KJJATSXiUPYXWlnoT0u-XKASWDSSuP0JEixG0QpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});